Core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import signin, signup, signout, profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('profile/', profile, name='profile'),

    path('', include('kinopoisk.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

kinopoisk/urls.py
from django.urls import path
from .views import *

app_name = "kinopoisk"

urlpatterns = [
    path('', main, name='main'),  # Главная страница.
    path('movies/', movie_list, name='movie_list'),  # Список всех фильмов.

    path('person_list/<str:person_type>/', person_list, name='person_list'),
    path('genres/', genre_list, name='genre_list'),  # Список всех жанров.
    path('movie/<int:movie_id>/', movie_detail, name='movie_detail'),  # Детали фильма.
    path('add_review/', add_review, name='add_review'),
    path('person/<int:person_id>/', person_detail, name='person_detail'),
    path('genre/<int:genre_id>/', genre_detail, name='genre_detail'),  # Фильмы по жанру.
]

Core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    favorite_movies = models.ManyToManyField(
        'kinopoisk.Movie',
        blank=True
    )
    avatar = models.ImageField(
        upload_to='avatars/',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

kinopoisk/models.py
from django.db import models
from Core.models import User


class MoviePerson(models.Model):
    class RoleType(models.TextChoices):
        ACTOR = 'actor', 'Actor'
        DIRECTOR = 'director', 'Director'

    name = models.CharField(max_length=255)
    birth_date = models.DateField(blank=True, null=True)
    photo = models.ImageField(
        upload_to="kinopoisk/images/person/photos/",
        blank=True, null=True)
    role = models.CharField(
        max_length=20, choices=RoleType.choices,
        blank=True, null=True
        )


class Genre(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)


class Movie(models.Model):
    title = models.CharField(max_length=355)
    description = models.TextField()
    release_date = models.DateField(null=True, blank=True)
    rating = models.FloatField(null=True, blank=True)
    # Продолжительность в минутах
    duration = models.PositiveSmallIntegerField()
    genres = models.ManyToManyField(Genre, related_name='movies')
    directors = models.ManyToManyField(MoviePerson, related_name='directed_movies')
    budget = models.PositiveIntegerField()
    actors = models.ManyToManyField(
        MoviePerson, related_name='acted_in_movies')
    poster = models.ImageField(
        upload_to="kinopoisk/images/movies/posters/",
        blank=True, null=True)


class MovieReview(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        null=True, related_name='reviews')
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE,
        related_name='reviews')
    text = models.TextField()
    likes = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

Core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from .models import User

def signup(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        r_password = request.POST.get('r_password')

        if password!=r_password:
            messages.error(request, 'Пароли не совпадают')
            return redirect('signup')
        
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Имя занято')
            return redirect('signup')

        User.objects.create_user(username=username, password=password)
        return redirect('signin')

    return render(request, 'Core/signup.html')

def signin(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if not user:
            return redirect('signin')
        
        login(request, user)
        return redirect('profile')
    
    return render(request, 'Core/signin.html')

def profile(request):
    user = request.user
    return render(request, 'Core/profile.html', {'user': user})

def signout(request):
    logout(request)
    return redirect('kinopoisk:main')

kinopoisk/views.py
from django.shortcuts import render, redirect
from .models import Movie, MoviePerson, MovieReview, Genre


def main(request):
    movies = Movie.objects.all()
    return render(request, 'kinopoisk/main.html', {'movies': movies})

def movie_list(request):
    movies = Movie.objects.all()
    return render(request, 'kinopoisk/movie_list.html', {'movies': movies})


def person_list(request, person_type):
    if person_type == 'actor':
        persons = MoviePerson.objects.filter(role=MoviePerson.RoleType.ACTOR)
        title = 'Актеры'
    else:
        persons = MoviePerson.objects.filter(role=MoviePerson.RoleType.DIRECTOR)
        title = 'Режиссеры'
    return render(request, 'kinopoisk/person_list.html', {'persons': persons, 'title': title})

def genre_list(request):
    genres = Genre.objects.all()
    return render(request, 'kinopoisk/genre_list.html', {'genres': genres})

def movie_detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(
        request,
        'kinopoisk/movie_detail.html',
        {
            'movie': movie,
            'reviews': MovieReview.objects.filter(movie_id=movie.id)
        }
        )  

def add_review(request):

        movie_id = request.POST.get('movie_id')
        review_text = request.POST.get('review_text')
        movie = Movie.objects.get(id=movie_id)

        MovieReview.objects.create(
            author=request.user,
            text=review_text,
            movie=movie
        )
        return redirect("kinopoisk:movie_detail", movie_id=movie_id)

def person_detail(request, person_id):
    person = MoviePerson.objects.get(id=person_id)

    if person.role == MoviePerson.RoleType.ACTOR:
        movies = person.acted_in_movies.all()
    else:
        movies = person.directed_movies.all()

    return render(request, 'kinopoisk/person_detail.html', {'person': person, 'movies': movies})

def genre_detail(request, genre_id):
    genre = Genre.objects.get(id=genre_id)
    movies = genre.movies.all()
    return render(request, 'kinopoisk/genre_detail.html', {'genre': genre, 'movies': movies})

templates/Core/profile.html
{% extends "base.html" %}

{% load static %}

{% block title %}Профиль{% endblock title %}

{% block content %}
<h1 style="text-align: center;">Профиль</h1>
<div style="width: 600px; text-align: center; border-radius: 10px solid gray; padding:20px; margin: 0 auto;">
    <h3>{{user.username}}</h3>
    {% if user.avatar %}
        <img src="{{ user.avatar.url }}" style="width: 100px; height: 100px;">
    {% endif %}  
</div>
{% endblock %}

templates/Core/signin.html
{% extends "base.html" %}

{% load static %}

{% block title %}Вход{% endblock title %}

{% block content %}
<h1 style="text-align: center;">Вход</h1>
<div style="width: 1000px; margin: 0 auto;">
    <form method="post" style="display: flex; flex-direction: column; width: 600px; margin: 0 auto;">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Имя пользователя" rquired>
        <input type="password" name="password" placeholder="Пароль" rquired>

        <button type="submit">Войти</button>
    </form>

</div>
{% endblock %}

templates/Core/signup.html
{% extends "base.html" %}

{% load static %}

{% block title %}Регистрация{% endblock title %}

{% block content %}

<h1 style="text-align: center;">Регистрация</h1>
<div style="width: 1000px; margin: 0 auto;">
    <form method="post" style="display: flex; flex-direction: column; width: 600px; margin: 0 auto;">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Имя пользователя" rquired>
        <input type="password" name="password" placeholder="Пароль" rquired>
        <input type="password" name="r_password" placeholder="Пвторный пароль" rquired>

        <button type="submit">Зарегистрироваться</button>
    </form>

    {% for message in messages %}
    <p><strong>{{ message }}</strong></p>
    {% endfor %}

</div>

{% endblock %}

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'kinopoisk:main' %}">КиноПоиск</a>
            <ul class="nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'kinopoisk:movie_list' %}">Фильмы</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'kinopoisk:person_list' person_type='actor' %}">Актеры</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'kinopoisk:person_list' person_type='director' %}">Режиссеры</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'kinopoisk:genre_list' %}">Жанры</a></li>
                <li class="nav-item"><a class="nav-link" href="/admin/">Админка</a></li>
            </ul>
            <ul class="nav">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signout' %}">Выход</a>
                </li>
                {% else %} 
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signin' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Зарегистрироваться</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock content %}
</body>
</html>

templates/incqludes/movie_listcard.html
<div style="display: flex; flex-wrap: wrap; gap: 20px; justify-content: center; max-width: 1200px; margin: auto;">
    {% for movie in movies %}
    <div style="width: 30%; min-width: 250px; display: flex;">
        <div style="border: 1px solid #ddd; padding: 10px; text-align: center; flex: 1; display: flex; flex-direction: column;">
            <img src="{{ movie.poster.url }}" style="width: 100%; height: auto;">
            <h5>{{ movie.title }}</h5>
            <p style="flex-grow: 1;">{{ movie.description }}</p>
            <h5>Жанры:</h5>
            <p>
                {% for genre in movie.genres.all %}
                    {{ genre.name }}
                {% endfor %}
            </p>
            <a href="{% url 'kinopoisk:movie_detail' movie_id=movie.id %}" style="background: #007bff; color: white; padding: 5px 10px; text-decoration: none; margin-top: auto;">Подробнее</a>
        </div>
    </div>
    {% endfor %}
</div>

templates/kinopoisk/genre_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ genre.name }}{% endblock title %}

{% block content %}
{% include "incqludes/movie_listcard.html" %}
{% endblock %}

templates/kinopoisk/genre_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Kinopoisk | Жанры{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Жанры</h1>
    <div class="row justify-content-center">
        {% for genre in genres %}
            <div class="col-md-3 col-sm-6 mb-3">
                <div class="card text-center shadow-sm border-0 genre-card">
                    <div class="card-body">
                        <p class="btn btn-outline-primary w-100 genre-button">
                            <a href="{% url 'kinopoisk:genre_detail' genre_id=genre.id %}">{{ genre.name }}</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<style>
    .genre-card {
        transition: transform 0.2s ease-in-out;
    }

    .genre-card:hover {
        transform: scale(1.05);
    }

    .genre-button {
        font-size: 1.2rem;
        text-transform: uppercase;
    }
</style>
{% endblock %}

templates/kinopoisk/main.html
{% extends "base.html" %}

{% load static %}

{% block title %}Главная{% endblock title %}

{% block content %}
<h1 class="text-center mt-5 ">Популярные фильмы:</h1>
<div style="display: flex; flex-wrap: wrap; gap: 20px; justify-content: center; max-width: 1200px; margin: auto;">
        {% for movie in movies %}
        <div class="">
            <div class="card" style="width: 18rem;">
                <img src="{{ movie.poster.url }}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ movie.title }}</h5>
                    <p class="card-text">{{ movie.description }}</p>
                    <p class="card-text">
                        <h5 class="card-title">Жанры:</h5>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }}
                        {% endfor %}
                    </p>
                    <a href="#" class="btn btn-primary">Подробнее о фильме...</a>
                </div>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

templates/kinopoisk/movie_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ movie.title }}{% endblock title %}

{% block content %}
<h1 style="text-align: center;">Информация о фильме: {{ movie.title }}</h1>
<div style="display: flex; flex-wrap: wrap; gap: 20px; justify-content: center; max-width: 1200px; margin: 0 auto;">
    <div style="width: 30%; min-width: 250px; display: flex;">
        <div style="border: 1px solid #ddd; padding: 10px; text-align: center; flex: 1; display: flex; flex-direction: column;">
            <img src="{{ movie.poster.url }}" style="width: 100%; height: auto;">
            <h5>{{ movie.title }}</h5>
            <p style="flex-grow: 1;">{{ movie.description }}</p>
            <h5>Жанры:</h5>
            <p>
                <ul style="list-style:none;">
                    {% for genre in movie.genres.all %}
                    <li style="matgin-top: 15px;">
                        <a href="{% url "kinopoisk:genre_detail" genre_id=genre.id %}" 
                           style="background: white; color: black; padding: 5px 10px; margin-top: auto; margin_bottom: 20px;">{{ genre.name }}</a>
                    </li>
                    {% endfor %}
                </ul>
                
            </p>
        </div>
    </div>
</div>
{% if request.user.is_authenticated %}
    <section style="margin: 0 auto; width: 1000px;">
        <h2>Оставить комментарии</h2>
        <form action="{% url "kinopoisk:add_review" %}" method="post" style="display: flex; flex-direction: column; width: 600px;margin: 0 auto; padding: 20px; border: 5px solid green;">
            {% csrf_token %}
            <textarea name="review_text" placeholder="Введите текст"></textarea>
            <button type="submit">Отправить отзыв</button>
            <input type="hidden" value="{{ movie.id }}" name="movie_id">
        </form>
    </section>
{% endif %}

<section style="margin: 0 auto; width: 1000px;margin-top: 40px; ">
    <h2>Комментарии</h2>
    {% for review in reviews %}
        <div style="border: 3px solid black;margin: 0 auto; padding: 40px; margin-bottom:10px;">
            <h3><strong>Автор: </strong>{{ review.author.username }}</h3>
            <h3><strong>Текст: </strong>{{ review.text }}</h3>
            <h3><strong>Лайки: </strong>{{ review.likes }}</h3>
            <h3><strong>Опубликован </strong>{{ review.created_at }}</h3>
        </div>
    {% endfor %}
</section>
{% endblock %}

templates/kinopoisk/movie_list.html
{% extends "base.html" %}

{% load static %}

{% block title %}{% endblock title %}

{% block content %}
{% include "incqludes/movie_listcard.html" %}
{% endblock %}

templates/kinopoisk/person_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}{% endblock title %}

{% block content %}
{% endblock %}

templates/kinopoisk/person_list.html
{% extends "base.html" %}

{% load static %}

{% block title %}{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">{{ title }}</h1>
    <div class="row justify-content-center">
        {% for person in persons %}
            <div class="col-md-3 col-sm-6 mb-3">
                <div class="card text-center shadow-sm border-0 genre-card">
                    <div class="card-body">
                        <img src="{{ person.photo.url }}" alt="">
                        <p class="btn btn-outline-primary w-100 genre-button">
                            <a href="{% url 'kinopoisk:person_detail' person_id=person.id %}">{{ person.name }}</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/kinopoisk/test.html
{% extends "base.html" %}

{% load static %}

{% block title %}{% endblock title %}

{% block content %}
<h1>{{ test }}</h1>
{% endblock %}